spring:
  datasource:
    url: jdbc:h2:file:/tmp/college_db
    driver-class-name: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # or create, create-drop, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  data:
    path:
      images: F:\Java Projects\prodcation\images-data
      videos: F:\Java Projects\prodcation\videos-data
